name: Release

on:
  push:
    tags:
      - '[0-9]*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update version in RollFor-WotLK.toc
        run: |
          sed -i "s/## Version: .*/## Version: ${{ env.VERSION }}/" RollFor-WotLK.toc

      - name: Commit and push version update
        # This allows the workflow to keep going even if the push fails
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add RollFor-WotLK.toc
          git commit -m "chore: Update version to ${{ env.VERSION }}" || echo "No changes to commit"
          git push origin HEAD:${{ github.event.repository.default_branch }}

      - name: Package and Release
        uses: BigWigsMods/packager@master
        with:
          # Use the local files we just modified
          upload-dir: .
          # Force the folder name inside the zip to match your TOC
          args: -n RollFor-WotLK -z RollFor-WotLK
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
