name: Release

on:
  push:
    tags:
      - '[0-9]*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Build zip
        run: |
          mkdir -p RollFor-WotLK
          rsync -av --exclude='.git' --exclude='.github' --exclude='.gitignore' \
            --exclude='.gitattributes' --exclude='.pkgmeta' --exclude='SoftRes' \
            --exclude='RollFor-WotLK' . RollFor-WotLK/
          zip -r RollFor-WotLK.zip RollFor-WotLK/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: RollFor-WotLK.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
